### ISSUE TITLE
travis cms behat tests currently broken

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-cms#2036]
As per artifacts available at https://s3.amazonaws.com/silverstripe-travis-artifacts/silverstripe/silverstripe-cms/304489358/304489362/index.html

Error output from selenium shows:

```
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
Nov 23, 2017 1:01:29 AM org.openqa.grid.selenium.GridLauncher main
INFO: Launching a standalone server
01:01:29.967 INFO - Java: Oracle Corporation 25.144-b01
01:01:29.969 INFO - OS: Linux 4.9.6-040906-generic amd64
01:01:29.983 INFO - v2.41.0, with Core v2.41.0. Built from revision 3192d8a
01:01:30.074 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: LINUX
01:01:30.177 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
01:01:30.178 INFO - Version Jetty/5.1.x
01:01:30.181 INFO - Started HttpContext[/selenium-server,/selenium-server]
01:01:30.242 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@2eee9593
01:01:30.242 INFO - Started HttpContext[/wd,/wd]
01:01:30.242 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
01:01:30.242 INFO - Started HttpContext[/,/]
01:01:30.247 INFO - Started SocketListener on 0.0.0.0:4444
01:01:30.247 INFO - Started org.openqa.jetty.jetty.Server@30dae81
01:01:31.876 INFO - Executing: [new session: Capabilities [{build=3146, browser=firefox, tunnel-identifier=3146.4, name=Behat feature suite, browserName=firefox, ignoreZoomSetting=false, tags=[Travis-CI, PHP 7.0.22]}]] at URL: /session)
01:01:31.895 INFO - Creating a new session for Capabilities [{build=3146, browser=firefox, tunnel-identifier=3146.4, name=Behat feature suite, browserName=firefox, ignoreZoomSetting=false, tags=[Travis-CI, PHP 7.0.22]}]
01:01:34.104 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: 'travis-job-silverstripe-silverstripe-c-304489362.travisci.net', ip: '172.17.0.71', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.6-040906-generic', java.version: '1.8.0_144'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:177)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:113)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:90)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:96)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:63)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:202)
	at org.openqa.selenium.remote.server.JsonHttpRemoteConfig.handleRequest(JsonHttpRemoteConfig.java:193)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:174)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:140)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
```

**Comment by tractorcow** [comment]
So far all of my research has pointed me towards "just upgrade selenium"

**Comment by tractorcow** [comment]
Oddly, these same tests run fine on framework travis build

https://travis-ci.org/silverstripe/silverstripe-framework/jobs/306118616

**Comment by tractorcow** [comment]
For reference, here are cms behat test logs: One from framework repo (works), and other from cms (broken)

[behat-cms-broken.txt](https://github.com/silverstripe/silverstripe-cms/files/1497903/behat-cms-broken.txt)
[behat-cms-working.txt](https://github.com/silverstripe/silverstripe-cms/files/1497904/behat-cms-working.txt)
